### ISSUE TITLE
CPU performance of FPS is slower than expected

### ISSUE THREAD

**Issue by lejafar** [rusty1s/pytorch_cluster#90] opened 2020-12-01 17:03 UTC
Hi @rusty1s,

Thanks for your work! I was trying out the fps implementation and found that is slower than doing it in pure Pytorch, any idea why this would be the case or if I'm missing something? (Both methods give the same result)

```python
import torch
from torch_cluster import fps

points = torch.Tensor(4, 4000, 3).uniform_(0, 1)

def custom_fps():
    global points
    B, N, C = points.shape

    # flatten points
    src = points.reshape(-1, C)
    batch = torch.Tensor([i for i in range(B) for _ in range(N)]).long()

    # compute
    out = fps(src, batch, ratio=0.5, random_start=False)
    return (out.reshape(B, -1).T - torch.tensor([i*N for i in range(B)])).T

def plain_fps():
    global points
    npoint = int(points.shape[1] * 0.5)
    B, N, C = points.shape

    centroids = torch.zeros(B, npoint, dtype=torch.long)
    distance = torch.ones(B, N) * 1e10

    farthest = torch.zeros(B, dtype=torch.long)

    batch_indices = torch.arange(B, dtype=torch.long)
    for i in range(npoint):
        centroids[:, i] = farthest
        centroid = points[batch_indices, farthest, :].view(B, 1, C)
        dist = torch.sum((points - centroid)**2, -1)
        mask = dist < distance
        distance[mask] = dist[mask]
        farthest = torch.max(distance, -1)[1]
    return centroids
```

When I time both on a single cpu I get:
```
$ taskset --cpu-list 79 python -m timeit -s 'import benchmark' -n 5 -r 5 -- 'benchmark.custom_fps()'
5 loops, best of 5: 6.34 sec per loop
$ taskset --cpu-list 79 python -m timeit -s 'import benchmark' -n 5 -r 5 -- 'benchmark.plain_fps()'
5 loops, best of 5: 1.37 sec per loop
```

**Comment by rusty1s** [comment] 2020-12-03 14:13
Thanks you so much for benchmarking :) It's true that `fps` on CPU is actually quite slow, and I found the cause of this. The reason was that I was computing distances via `torch.norm` which is rather slow in comparison to `pow(2).sum()`. This is now fixed.

**Closed** 2020-12-03 14:18 UTC

**Comment by lejafar** [comment] 2020-12-03 14:46
For completeness, after the change:
```
$ taskset --cpu-list 79 python -m timeit -s 'import benchmark' -n 5 -r 5 -- 'benchmark.custom_fps()'
5 loops, best of 5: 1.1 sec per loop
$ taskset --cpu-list 79 python -m timeit -s 'import benchmark' -n 5 -r 5 -- 'benchmark.plain_fps()'
5 loops, best of 5: 1.35 sec per loop
```

**Comment by lejafar** [comment] 2020-12-03 15:35
And I see you already addressed my next issue, the lack of parallelisation 🙂

Before:
```
$ taskset --cpu-list 76,77,78,79 python -m timeit -s 'import benchmark' -n 5 -r 5 -- 'benchmark.custom_fps()'
5 loops, best of 5: 1.1 sec per loop
$ taskset --cpu-list 76,77,78,79 python -m timeit -s 'import benchmark' -n 5 -r 5 -- 'benchmark.plain_fps()'
5 loops, best of 5: 880 msec per loop
```
After:
```
$ taskset --cpu-list 76,77,78,79 python -m timeit -s 'import benchmark' -n 5 -r 5 -- 'benchmark.custom_fps()'
5 loops, best of 5: 310 msec per loop
$ taskset --cpu-list 76,77,78,79 python -m timeit -s 'import benchmark' -n 5 -r 5 -- 'benchmark.plain_fps()'
5 loops, best of 5: 879 msec per loop
```

**Comment by rusty1s** [comment] 2020-12-03 16:33
Awesome :)
